**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np


###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
#Code here
a, b = map(int, input("Enter two numbers: ").split())
rand=np.random.random((a,b))
avg=np.mean(rand)
print(avg)

Enter two numbers:  6 6


0.476450676818729


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [18]:
#Code here
def array(a,b):
       arr=np.arange(16).reshape(a,b)
       arr[:,]=1
       arr[1:3,1:3]=0
       return arr
a,b=map(int,input().split())
arr=array(a,b)
print(arr)

 4 4


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [91]:
#Code here
arr=np.arange(10)
for i in arr:
    if i%2==0:
        arr[i]=0
    else:
        arr[i]=1

print(arr)

#  another option 
arr=np.arange(10)
arr[arr%2==0]=0
arr[arr%2==1]=1
print(arr)



[0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [3]:
import numpy as np

mat = np.eye(3,4)  # 3x3 Identity Matrix
print(mat)


#  another way 

a,b=map(int,input().split())
arr=np.zeros((a,b))
for i in range(a-1):
    mat[i][i] = 1  # Placing 1s in diagonal positions

print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


 3 4


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [20]:
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [30]:
import numpy as np

# 5x5 empty matrix
matrix = np.zeros((5, 5), dtype=int)

# Filling each row with values from 0 to 4 using for loop
for i in range(5):
    matrix[i] = np.arange(5)

print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [25]:
#Code here
arr=np.array([1 ,2, 3, 4, -8, -10],dtype=float)
arr[::-1]

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [33]:
#Code here
a,b=map(int,input().split())
arr=np.random.random((a,b))
np.round(arr*100)

size=np.size(arr)
print("the total number of elements in array is : ")

 5 9


45

In [ ]:
np.exp()

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [49]:
def date_array(start,end):
    start_date=np.datetime64(start)
    end_date=np.datetime64(end)
    arr=np.arange(start_date,end_date)
    return arr
date_array(start = '2022-12-01', end = '2022-12-06')


array(['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [64]:
#code here
a,b=map(int,input().split())
r=np.round(matrix*100)
print(r)
mean=np.mean(r)
n=np.round(mean)
print(n)
s=r-n
print(s)

 5 6


[[98. 44. 24. 13. 53.]
 [77. 50. 22. 35. 98.]
 [49. 22. 51. 13. 84.]
 [34. 31.  5. 80. 91.]
 [15. 34. 19. 41. 31.]]
45.0
[[ 53.  -1. -21. -32.   8.]
 [ 32.   5. -23. -10.  53.]
 [  4. -23.   6. -32.  39.]
 [-11. -14. -40.  35.  46.]
 [-30. -11. -26.  -4. -14.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

In [83]:
sc=np.arange(25).reshape(5,5)
print(sc)
sc[:,[4,3]]=sc[:,[3,4]]
print(sc)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  4  3]
 [ 5  6  7  9  8]
 [10 11 12 14 13]
 [15 16 17 19 18]
 [20 21 22 24 23]]


###`Q-16:` Replace odd elements in arrays with -1.

In [87]:
#Code here
a,b=map(int,input().split())
arr=np.arange(25).reshape(a,b)
print(arr)
arr[arr%2!=0]=-1
print(arr)

 5 5


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]
 [10 -1 12 -1 14]
 [-1 16 -1 18 -1]
 [20 -1 22 -1 24]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [104]:
#Code here
arr1=np.arange(5).reshape(1,5)
arr2=np.arange(6,11).reshape(1,5)
print("arr1  ",arr1,"\n arr2 ",arr2)
max_values = np.maximum(arr1, arr2)
print(max_values)

arr1   [[0 1 2 3 4]] 
 arr2  [[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [117]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)
x=arr1[:,::2]
xmin=np.min(x,axis=0)
xmax=np.max(x,axis=0)
xnormalized=(x-xmin)/(xmax-xmin)
print(xnormalized)

[[2210 7538 7285 5344 7272]
 [9018 2813 6017 9318 4623]
 [5576 5646 5815 8844 7945]
 [4122 1821 2783 7966 4447]
 [ 525 5543 4256 6705 3346]
 [3627 9519 8505   86 7217]
 [7433 4043 6686  301  161]
 [ 750  394 3208 3503 6886]]
[[0.19839868 0.78678784 0.9135406 ]
 [1.         0.565187   0.57322713]
 [0.59472507 0.52988466 1.        ]
 [0.42352526 0.         0.55061665]
 [0.         0.25742747 0.40917266]
 [0.36524196 1.         0.90647482]
 [0.81337572 0.68210416 0.        ]
 [0.02649241 0.07427473 0.8639517 ]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [40]:
arr = np.array([12,34,40,7,1,0])
n = int(input("Enter value of n: "))
# `n` चे validation करणे
if n > len(arr) or n <= 0:
    print("Invalid value of n")
else:
    # पहिल्या `n` एलिमेंटमधून max शोधा
    m = arr[0]
    for i in range(n):
        if m < arr[i]:
            m = arr[i]
            
    print("Maximum value in first", n, "elements:", m)
# m=np.max(arr,n)
# print(m)

Enter value of n:  2


Maximum value in first 2 elements: 34


In [42]:
arr
np.sort(arr)
if n<len(arr):
    print(arr[n])
    

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [151]:
#code here
arr=np.array([1,2,3])
L=len(arr)
n=L**2
for i in range(n):
   arr[i]= np.arange(1,4)
   print(arr,end=" ")    

ValueError: setting an array element with a sequence.

In [152]:
np.tile(arr,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [153]:
import numpy as np

arr = np.array([1, 2, 3])

L = len(arr)
n = L**2  # 3^2 = 9

# नवीन रिकामी लिस्ट तयार करतो
result = []

for i in range(n):
    result.append(arr[i % L])  # i % L चा उपयोग रिपीट करण्यासाठी होतो

# NumPy ऍरेमध्ये कन्व्हर्ट करतो
result = np.array(result)

print(result)



[1 2 3 1 2 3 1 2 3]
