#  Tricky function in array using  np build the thous fn 


In [2]:
import numpy as np



In [7]:
#  sort fn

arr=np.random.randint(1,50,15).reshape(5,3)
print(arr)
np.sort(arr,axis=1) # 0 is the row and 1 is the clm 

[[28 46 27]
 [24 18 46]
 [33  5 27]
 [21 45  2]
 [36  7 17]]


array([[27, 28, 46],
       [18, 24, 46],
       [ 5, 27, 33],
       [ 2, 21, 45],
       [ 7, 17, 36]], dtype=int32)

In [8]:
# append fn
arr=np.random.randint(1,50,15).reshape(5,3)
print(np.size(arr))
m=np.append(arr,27)
print(m)
print(np.size(m))


15
[22  4 31 44 23 17 17 41 48 24 19 21 13 48  7 27]
16


In [10]:
# concatenate the 2 or more arrays 
a=np.arange(12).reshape(4,3)
b=np.arange(12).reshape(4,3) 
 
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

In [11]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# uniqu element in array 


In [14]:
arr=np.array([1,1,1,2,2,4,1,2,3,5,4,6,8,6,2,88,6,2,5,8,12,3,8])
np.unique(arr)

array([ 1,  2,  3,  4,  5,  6,  8, 12, 88])

In [16]:
#  expand_dims
#  1d la 2d and 2d la 3d madhe convert kareaych kam kartro 
np.expand_dims(arr,axis=0) # row or colum both vr karta yenare op


array([[ 1,  1,  1,  2,  2,  4,  1,  2,  3,  5,  4,  6,  8,  6,  2, 88,
         6,  2,  5,  8, 12,  3,  8]])

In [17]:
#  whare fn to filter the data 
# np.where(condition ,ture,false)
np.where(arr>50,0,arr) 

array([ 1,  1,  1,  2,  2,  4,  1,  2,  3,  5,  4,  6,  8,  6,  2,  0,  6,
        2,  5,  8, 12,  3,  8])

In [23]:
print(arr)
a=np.max(arr)
print(a)

[ 1  1  1  2  2  4  1  2  3  5  4  6  8  6  2 88  6  2  5  8 12  3  8]
88


In [25]:
#  prefix sum of the elemnt in array 

np.cumsum(arr)

array([  1,   2,   3,   5,   7,  11,  12,  14,  17,  22,  26,  32,  40,
        46,  48, 136, 142, 144, 149, 157, 169, 172, 180])

In [39]:
#  cumprod -> cumulated product yani hr ek number uske prefix array  ka product 
arr=np.arange(1,50)
print(arr)
product_arr=np.cumprod(arr)
print(product_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
[                   1                    2                    6
                   24                  120                  720
                 5040                40320               362880
              3628800             39916800            479001600
           6227020800          87178291200        1307674368000
       20922789888000      355687428096000     6402373705728000
   121645100408832000  2432902008176640000 -4249290049419214848
 -1250660718674968576  8128291617894825984 -7835185981329244160
  7034535277573963776 -1569523520172457984 -5483646897237262336
 -5968160532966932480 -7055958792655077376 -8764578968847253504
  4999213071378415616 -6045878379276664832  3400198294675128320
  4926277576697053184  6399018521010896896  9003737871877668864
  1096907932701818880  4789013295250014208  2304077777655037952
   -7060926234624

In [37]:
# percentile mean yat jo  num max to 100% rahanar and jo  min to 0% percent 
pre=np.percentile(arr,100)
print(pre)

5.0


In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
#  histogram fn 
# he aapan arr madhe sodu ki ya range madhe kiti element aahe in aaray  

total=np.histogram(arr,bins=[0,50,100]) # 0 to 50 madhe 49 element aahet but tyat 50 bovet up to 100 0 eleement aahet 

print(total)

(array([49,  0]), array([  0,  50, 100]))


In [46]:
#  isin he multiple items la search karnya sathi use kel jt 
# eg arrya madhe 25, 99,55,89 he element aahe ki nahi he check karu 
a=[25, 99,55,89] # only 25 sapdla  but je je sapdle asyte to data aaplya la true milala asta 
np.isin(arr,a)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [50]:
#  put fn are use to change the multple item value in array 
# eg put(arr,provide ind number in array form , jya valvue takaych aahe tya provide karne]) 
np.put(arr,[0,2,5],[10000,55,365246])
arr

array([ 10000,      2,     55,      4,      5, 365246,      7,      8,
            9,     10,     11,     12,     13,     14,     15,     16,
           17,     18,     19,     20,     21,     22,     23,     24,
           25,     26,     27,     28,     29,     30,     31,     32,
           33,     34,     35,     36,     37,     38,     39,     40,
           41,     42,     43,     44,     45,     46,     47,     48,
           49])

In [54]:
#  delete fn provide array and it's index
arr
print(np.delete(arr,[0,2,4])) # 0 ,0,4 ya index che items ddlet zale 

[     2      4 365246      7      8      9     10     11     12     13
     14     15     16     17     18     19     20     21     22     23
     24     25     26     27     28     29     30     31     32     33
     34     35     36     37     38     39     40     41     42     43
     44     45     46     47     48     49]
