In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
np.identity(5)
np.ones(5)
print(a.itemsize)
print(a.nbytes)
print(a.size)


8
40
5


In [5]:
#  2D & 3D numpy array 
D2=np.array([[1,2,3],[4,5,6]])
print(D2)
D3 =np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("3d array is : ", D3)

[[1 2 3]
 [4 5 6]]
3d array is :  [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
arr=np.array([1,4,5,6],dtype=str)
arr

array(['1', '4', '5', '6'], dtype='<U1')

In [7]:
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.ones((3,4))
# np.random
arr=np.random.random((3,4))
arr

array([[0.01839995, 0.62512182, 0.76749211, 0.62370967],
       [0.22023626, 0.7914739 , 0.84050712, 0.32523827],
       [0.1805845 , 0.47251097, 0.58114976, 0.96211326]])

In [9]:
# 
arr.shape

(3, 4)

In [10]:
#  scler in python 
arr=np.arange(20).reshape(4,5)

# scaler form use 
#  power od the number using scaler 
power=arr**2
print(power)

tb2=arr*2
print(tb2)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#  vectore form in  numpy 
a1=np.arange(20).reshape(5,4)
a2=np.arange(19,39).reshape(5,4)
a3=a1+a2
print(a3)

[[19 21 23 25]
 [27 29 31 33]
 [35 37 39 41]
 [43 45 47 49]
 [51 53 55 57]]


In [13]:
#  fn in numpy array 
a=np.min(a3)
print(a)
max=np.max(a3)
print(max)
sum=np.sum(a3)
print(sum)
product=np.prod(a3)
print(product)

19
57
760
6287361309452331121


In [14]:
#  axis parameter are use for row and  operation axis=1 yani row and axis=0 yani clo vr opration honar 
#  calculate the sum of every colum 
am=np.arange(20).reshape(5,4)
print(am)
print("the sum of the colom is ")
col_sum=np.sum(am,axis=0)
print(col_sum)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
the sum of the colom is 
[40 45 50 55]


In [15]:
row_min=np.min(a3,axis=1)
print(row_min)

[19 27 35 43 51]


In [16]:
#  statistic fn in numpy
#  mean/median / std(staderd daviationb) / var (variance )
mean=np.mean(a3,axis=0)
print(mean)

[35. 37. 39. 41.]


In [17]:
m1=np.arange(9).reshape(3,3)
m2=np.arange(9,18).reshape(3,3)

dot=np.dot(m1,m2)
print("dot product pf the 2 ")

dot product pf the 2 


In [60]:
arr1=np.arange(10).reshape(5,2)
arr2=np.arange(10,20).reshape(5,2)
a=np.random.random((4,5))
print(a)
#  to conver into interger by using floor 
np.floor(np.random.random((4,4))*100)

#  convert in to  ceil
b=np.arange(4,4)
np.ceil(np.random.random((4,5))*100)


[[0.5165892  0.09636003 0.08376195 0.24106269 0.84244091]
 [0.42604494 0.02661173 0.82227433 0.35478662 0.80570197]
 [0.70016044 0.69058135 0.05293815 0.38272155 0.12190283]
 [0.80083135 0.74643638 0.6014809  0.61977452 0.11025701]]


array([[ 79.,  47.,  61.,  17.,  82.],
       [  4.,  69.,  97.,  33.,  88.],
       [ 73.,  14.,  31., 100.,  28.],
       [ 56.,  14.,   7.,  43.,  79.]])

In [67]:
#  indexing and sclicing in arr 

d2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d2)
d2[-1] # in 2D array to  take a -1 in ind so give a last row in the arra

idx5=d2[1,1]
print(idx5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [80]:
d3=np.array([
    [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ],
    [ [13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24] ]
])
print(d3)
d3[-1]

print(d3[0,2,3])

print(d3[1,2,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
12
23


In [87]:
#  sclising in array 
arr1=np.arange(10)
print(arr1) 
#  to print only even number 
arr1[0::2]
#  to print(odd number 

arr1[1::2]

arr1[::-1]

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [99]:
#  get the element in 2d array 
print(d2)
an=d2[:,2] # yani : mean all row's jya colom 3 madhe yata aahet 
print(an)

#  print the middle row only 
d2[2:] # 2nd row : mean ti row madhe je pn column element yyeta aahet te all 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]


array([[7, 8, 9]])

In [162]:
#  pribnt  5 6
          #8 9

A=d2[0:,1:3]
print(A)

[[2 3]
 [5 6]
 [8 9]]


In [149]:
#  1 3 
#  7 9


B=d2[::2,::2]
print(B)

[[2]
 [8]]


In [170]:
print(d2)
d2[1,::2]
d2[1,::2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 6])

In [186]:
#   2 3
#   5 6
print(d2)
d2[0:2:,1::]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [203]:
d2[0:2,::2]
d2[1:,::2]
d2[0::,2:3:]

array([[3],
       [6],
       [9]])

In [218]:
d3=np.arange(27).reshape(3,3,3)
print(d3)
d3[1] # find 2nd m 

print(d3[1,1::2]) # 12,13,14

d3[2,2,0::] # 3nd m 2nd  row  print 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[12 13 14]]


array([24, 25, 26])

In [229]:
#  find the ocrner lement in matrix 2 

d3[2,::2,::2]
d3[1,0:,1::2]

array([[10],
       [13],
       [16]])

In [232]:
#  1st matrix and 3nd matrix how to get 
d3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [236]:
#  print 1matrix 2 row  3,4,5
d3[0,1::2]

array([[3, 4, 5]])

In [249]:
#  print the 2m 3rd column
print(d3)
d3[1,:,2::]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[11],
       [14],
       [17]])

In [251]:
d3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [287]:
d3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [293]:
#  fool apply on numpyarr
c=0
for i in d3:
    c+=1
    print(i,c," -> row ")


[[0 1 2]
 [3 4 5]
 [6 7 8]] 1  -> row 
[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 2  -> row 
[[18 19 20]
 [21 22 23]
 [24 25 26]] 3  -> row 


In [306]:

#  firn the sub row also 
c=0
a=1
for i in d3:
    a+=1
    c=0
    for j in d3:
        c+=1
        print(j,"row ","c->",c,"a -> ",a)

[[0 1 2]
 [3 4 5]
 [6 7 8]] row  c-> 1 a ->  2
[[ 9 10 11]
 [12 13 14]
 [15 16 17]] row  c-> 2 a ->  2
[[18 19 20]
 [21 22 23]
 [24 25 26]] row  c-> 3 a ->  2
[[0 1 2]
 [3 4 5]
 [6 7 8]] row  c-> 1 a ->  3
[[ 9 10 11]
 [12 13 14]
 [15 16 17]] row  c-> 2 a ->  3
[[18 19 20]
 [21 22 23]
 [24 25 26]] row  c-> 3 a ->  3
[[0 1 2]
 [3 4 5]
 [6 7 8]] row  c-> 1 a ->  4
[[ 9 10 11]
 [12 13 14]
 [15 16 17]] row  c-> 2 a ->  4
[[18 19 20]
 [21 22 23]
 [24 25 26]] row  c-> 3 a ->  4


In [310]:
# Printing 3D array elements
for i in range(len(d3)):  # Iterate over depth
    for j in range(len(d3[i])):  # Iterate over rows
        for k in range(len(d3[i][j])):  # Iterate over columns
            print(d3[i][j][k], end=" ")  # Print elements
        print()  # New line for clarity
    print()  # Extra line between depth levels


0 1 2 
3 4 5 
6 7 8 

9 10 11 
12 13 14 
15 16 17 

18 19 20 
21 22 23 
24 25 26 



In [319]:
# using a fn also print the 3d array 
for i in np.nditer(d3):
    print(i,end=" ")
     

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [323]:
#  transpose of the matrix
print(d3)
print("the transpose of the d3 matrix ")
a=np.transpose(d3) 
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
the transpose of the d3 matrix 
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [329]:
a=np.arange(12).reshape(4,3)
print(a)
print("\ntranspose of the a is \n ")
b=np.transpose(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

transpose of the a is 
 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [339]:
#  another syntax for transpose matrix
t1=a1.T 
a2=np.arange(12).reshape(4,3)
t2=a2.T
print(t1)
print(t2)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


# ravel 
nD -> to 1D  

In [340]:
#  ravel fn in numpy array 
#  the use of the ravel fn in the np  array  if to cponvert the any type of array in 1d array 
a2.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [355]:
# Stacking in arrays 
#  type's 
#  horizental  jr a2 a1 madhe add hot asel tr a1 madhe number of coloum ^ increase honar 

a1 = np.array([[1, 2], [3, 4]])  # (2x2)
a2 = np.array([[5, 6], [7, 8]])  # (2x2)
print("a1 arr is : \n",a1)
print("a2 arr is : \n",a2)
# Horizontal stacking (columns वाढतील)
h = np.hstack((a1, a2))
print("\n",h)

# #  vertical 
v=np.vstack((a1,a2))
print("\n",v)

a1 arr is : 
 [[1 2]
 [3 4]]
a2 arr is : 
 [[5 6]
 [7 8]]

 [[1 2 5 6]
 [3 4 7 8]]

 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [369]:
#  spliting in np 
# he just ap[osite aahe stack chya mean stack jodaycha kam karto and he dodaych kam karto   
#  jr horihental todal tr matrix (a1,2) 2 ,2 colum reprate honar 
# eg

# Creating a 3x3 matrix
a1 = np.arange(12).reshape(4, 3)
print("Original Array:\n", a1)

# Horizontally splitting into 3 equal parts (each 3x1)
r = np.hsplit(a1,3)
print("\nSplitted Arrays:")
for arr in r:
    print(arr)

Original Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Splitted Arrays:
[[0]
 [3]
 [6]
 [9]]
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]


In [366]:
# 3x3 matrix tayar karat ahe
a1 = np.arange(12).reshape(4, 3)
print("Original Array:\n", a1)

# Matrix cha 3 vertical parts madhe split karto (pratyek 1 row asel)
r = np.vsplit(a1, 2)

print("\nVertically Splitted Arrays:")
for arr in r:
    print(arr)

Original Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Vertically Splitted Arrays:
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
